### ISSUE TITLE
Allow or Disallow Tile Size Hyperparameter in 3DUNet

### ISSUE THREAD

**Issue by DilipSequeira** [mlcommons/inference_policies#216]
From Alex in https://github.com/mlcommons/inference_policies/issues/213:

_We believe that steps 1-5 should not count against benchmark time and steps 6-8 could be left to the submitters to optimize (i.e. change the tile size) as long as they meet the expected accuracy or above. Indeed step 8 can probably take place on an accelerator. However it is to my understanding that the Inference closed division doesn't allow hyperparameter change. So submitters have to go with 128x128x128. Is this true?_

My reading of the model equivalence rules 

_All implementations are allowed as long as the latency and accuracy bounds are met and the reference weights are used._

is that they do allow for hyperparameters. Given that the network is fully convolutional and the pre- and post-processing can be adjusted for tile size, we would need to specifically prohibit variation in tile size in the model equivalence rules. There is precedent for this: we outlawed changing the beam width in GNMT in 0.5.

**Comment by tjablin** [comment]
I'm not sure the beam width decision is good precedent. Changing beam width radically alters the total amount of work the program does. Altering tile size keeps work more or less constant. Is allowing variable tile-size really so harmful? I can imagine that different submitters would prefer different tile sizes based on the width of their matrix-multiply hardware and the size of their caches and scratchpads. I don't think their are too many tile-sizes to exhaustively search, particularly since I think most submitters will prefer a power-of-two tile size.

**Comment by DilipSequeira** [comment]
With some reasonable restrictions, I don't think variable tile size is harmful per se. 

The larger question is whether the WG wants to take on the complexity of hyperparameters. 
* review is arguably complicated enough without hyperparameter borrowing
* I would not be surprised to see QAT weight contributions that work for a given set of hyperparameters but don't generalize
* If model equivalence allows you to pick a tile size, it also allows you to run untiled. Running 3DUNet untiled is, in the limit, 8x less work.

**Comment by DilipSequeira** [comment]
> If the network is fully convolutional, the QAT weights should just work, right?

The code that slices and combines is a function of network size - that's why there's currently one tile size that works best from an accuracy perspective. So if I were QAT'ing this, I might do it with the hyperparameter combination at which I was going to run, using the post-recombination loss.

Even in this case, there are potentially a lot of viable combinations - many accelerators are efficient on tile sizes that are e.g. multiples of 16 or 32. Tiles don't need to be cubic. You can reduce tile overlap. Etc.

**Comment by DilipSequeira** [comment]
Would you be willing to consider using a cubic tile size and then batching tiles for optimal sizing?

**Comment by rnaidu02** [comment]
@DilipSequeira  The batching option you suggested is same as the original proposal. Per my understanding, batching option requires cubic tiles to have overlap and requires 3x of 128x128x128 to cover area of 256x128x128. The compute will be 1.5x of the required as you need cubic tiles with a stride of 64. We should let the slice to be dynamic as long as the inference meets the desired accuracy target. Intel team contacted folks at a medical imaging company to find their practice, and they apparently don't go with fixed slice size and decide the slice size as long as it meets the  accuracy target.

**Comment by DilipSequeira** [comment]
@rnaidu02 the original proposal allows no variation in tile size. So what I'm asking is not the same. 

We share an understanding that allowing variation in tile size will allow submitters to produce more efficient implementations, and also that it would be reasonable thing to do in production. 

The tradeoff is the additional complexity for MLPerf - e.g. if every submitter chooses a different tile size, and then submits a quantized model based on that tile size, the benchmark can become unmanageable. That's why MLPerf would prefer not to have hyperparameters at all, or if that's not possible, to minimize the size of the hyperparameter space. So the question is: what is the smallest hyperparameter space that Intel believes is reasonable?

**Comment by rnaidu02** [comment]
@DilipSequeira May be I misunderstood your proposal. As an alternative to a tile size of 256x128x128 your proposal allow 3 overlapping tiles of 128x128x128 with a stride of 64 right?

We looked at the sizes of image scans from Kits19 and found that the image sizes are of Nx512x512 where N varies from 34 to 683 from a small sample of images from the data set. Based on this observation, our proposal  to have N as 128 and the 2nd and 3rd dimension to have starting value of 128 and increment by 128 and 256 - that results in tile size combinations of 128x128x128, 128x128x256,128x256x256,128x256x512,128x512x512.

**Comment by DilipSequeira** [comment]
> As an alternative to a tile size of 256x128x128 your proposal allow 3 overlapping tiles of 128x128x128 with a stride of 64 right?

Correct. 

It's not obvious to me why 128x128x512 isn't valid tile size in your proposal - can you elaborate on that?

Thanks for defining a smaller set; I'm not sure how to evaluate the tradeoff between this smaller one and the earlier one (128 x powers of 2 on all axes) which seems to me more natural.

In any case, if we're going to have tile hyperparameters, I suggest we also allow untiled.

**Comment by tjablin** [comment]
This is kind of pedantic, but I don't think "tile size" is a hyperparameter per se. A hyperparameter is a parameter whose value is used to control the learning process. Tile size doesn't control the learning process.

**Comment by DilipSequeira** [comment]
Pablo did some experiments on accuracy vs tile size.

![Accuracy vs Tile Size](https://user-images.githubusercontent.com/8258612/119164336-2ac9a300-ba11-11eb-8bbc-43c311be294a.PNG)

**Comment by tjablin** [comment]
Thanks for the results! Can you give more details about how these experiments were run? Is this the result of retraining the model for each tile size or reusing the weights from 128^3? What sort of numerics were used?

**Comment by tjablin** [comment]
How does accuracy at 128^3 at FP32 compare with FP16?

**Comment by DilipSequeira** [comment]
It's a different dataset, so the accuracies aren't comparable.

**Comment by pribalta** [comment]
@tjablin The model is trained by using sub-volumes of 128^3 dimensions, as this is the way it was prescribed in the original paper and that we follow in the MLPerf Training benchmark. Since the model is fully convolutional, once it's trained it can be applied seamlessly to infer over volumes of different dimensions. For reference, in the previous edition we were also training using 128^3 cubes, but we were abe to achieve SOTA accuracy by inferring over the full volume. The reason why this is hard to do using KITS19 is because of class imbalance (i.e., lots of background, smaller lesions).

As Dilip said, the results are obtained using FP16 precision. To the best of our knowledge, there is no accuracy loss compared to using FP32. As for the difference between targets (0.85300 DICE vs ~0.91 DICE), the reason for it is that we are moving from the BRATS19 dataset to the KITS19 dataset, so tasks are different and thus, final accuracy is also different. The most important thing to keep in mind is that our model is able to reproduce the SOTA accuracy on KITS19 achieved by 3D-UNet on this dataset (0.91ish DICE ) as it did for BRATS19 (0.853 DICE).

We collected these experiments by adding small tweaks to the training reference implementation. We are happy to share a diff in case you want to review the changes or run it on your local setup.

**Comment by rnaidu02** [comment]
Thank you Pablo and Dilip for your explanation and the effort to run inference under different tile sizes to measure the accuracy. @pribalta I have few questions. When you run inference using 160^3 tile size, did you use a stride of 80 pixels (half the size of tile size)? With the existing code can you run inference on whole image of 192x384x384 instead of using cubic tiles - in this case do you expect to have accuracy lower than the SOTA accuracy of 0.91 DICE score?

**Comment by rnaidu02** [comment]
On 6/8/2021, WG agreed to have tile size of 128x128x128 with a stride of 64 for 3D-UNet inference with KITS19 dataset.
